project_id       = "fast-ability-439911-u1"
region           = "us-central1"
vpc_name         = "my-vpc"
subnet_name      = "my-subnet"
ip_range_pods    = "pods-range"
ip_range_services = "services-range"
gke_cluster_name = "my-gke-cluster"
